# reproducibility
deterministic: False
random_seed: 42

# training

pl_trainer:
  fast_dev_run: False # Enable this for debug purposes
  gpus: 0
  precision: 32
  max_epochs: 1
  accumulate_grad_batches: 1
  num_sanity_val_steps: 2
  gradient_clip_val: 10.0

monitor_metric: "val_loss"
monitor_metric_mode: "min"

early_stopping:
  patience: 1
  verbose: False
